export const AUDIT_ACTIONS = {
  ADMIN_CREATED: "ADMIN_CREATED",
  ADMIN_ACTIVATED: "ADMIN_ACTIVATED",
  ADMIN_DEACTIVATED: "ADMIN_DEACTIVATED",
  ADMIN_PROMOTED_TO_SUPER_ADMIN: "ADMIN_PROMOTED_TO_SUPER_ADMIN",
  SUPER_ADMIN_DEMOTED_TO_ADMIN: "SUPER_ADMIN_DEMOTED_TO_ADMIN",
  ADMIN_TEMPORARY_PASSWORD_REISSUED: "ADMIN_TEMPORARY_PASSWORD_REISSUED",
  SUPER_ADMIN_BOOTSTRAPPED: "SUPER_ADMIN_BOOTSTRAPPED",
  COURSE_CREATED: "COURSE_CREATED",
  COURSE_UPDATED: "COURSE_UPDATED",
  COURSE_ADMIN_ASSIGNED: "COURSE_ADMIN_ASSIGNED",
  COURSE_ADMIN_UNASSIGNED: "COURSE_ADMIN_UNASSIGNED",
  COURSE_PRIMARY_ADMIN_CHANGED: "COURSE_PRIMARY_ADMIN_CHANGED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
